name: 'dbt_utsikt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_utsikt'
flags:
  send_anonymous_usage_stats: False

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ['docs']

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
models:
  dbt_utsikt:
    # Config indicated by + and applies to all files under models/example/
    # Farger valgt fra her: https://aksel.nav.no/grunnleggende/styling/design-tokens#h042525372dcd
    staging:
      +materialized: ephemeral
      +docs:
        +node_color: '#33aa5f' #grønn
    intermediate:
      +materialized: view
      +docs:
        +node_color: '#3386E0'  #blå    
    marts:
      agg:
        +materialized: view
        +docs:
          +node_color: '#368DA8' # turkis
      fak:
        +materialized: incremental
        +docs:
          +node_color: '#8269A2' #lilla

snapshots:
  dbt_utsikt:
    +docs:
      +node_color: '#e6b400' #gul

data_tests:
  dbt_utsikt:
    +docs:
      +node_color: '#cc79a7' #rosa
