dbt_utsikt:
  target: "{{env_var('TARGET_ENV', 'dev')}}"
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: utsikt-dev-3609
      dataset: venteregister 
      threads: 4 

    prod:
      type: bigquery
      method: oauth
      project: utsikt-prod-2dfe
      dataset: venteregister 
      threads: 4