version: 2

sources:
    - name: venteregister_name
      description: .
      database: 
      schema: venteregister
      tables:
          - name: t_faggruppe
            description: .
          - name: t_fagomraade
            description: .
          - name: t_vent_beregning
            description: .
          - name: t_vent_stoppnivaa
            description: .
          - name: t_vent_stoppstatus
            description: .
          - name: t_vent_statuskode
            description: .