version: 2

sources:
    - name: OS
      description: Tabeller fra OppdragZ scehma Q2 (dev) eller T1 (prod).
      database:
      schema: OS
      tables:
          - name: t_faggruppe
          - name: t_fagomraade
          - name: t_vent_beregning
            config:
              freshness:
                warn_after: { count: 3, period: day }
                error_after: { count: 4, period: day }
              loaded_at_field: tidspkt_reg
          - name: t_vent_stoppnivaa
            config:
              freshness:
                warn_after: { count: 3, period: day }
                error_after: { count: 4, period: day }
              loaded_at_field: tidspkt_reg
          - name: t_vent_stoppstatus
            config:
              freshness:
                warn_after: { count: 3, period: day }
                error_after: { count: 4, period: day }
              loaded_at_field: tidspkt_reg
          - name: t_vent_statuskode

    - name: venteregister
      description: Tabeller som tilhørerer venteregisteret i OppdragZ.
      database:
      schema: venteregister
      tables:
          - name: int_min_kombo_til_snapshot