version: 2

sources:
    - name: OS_Q2
      description: .
      database:
      schema: OS_Q2
      tables:
          - name: t_faggruppe
            description: .
          - name: t_fagomraade
            description: .
          - name: t_vent_beregning
            description: .
          - name: t_vent_stoppnivaa
            description: .
          - name: t_vent_stoppstatus
            description: .
          - name: t_vent_statuskode
            description: .