name: Apply Union configuration

on:
  push:
    branches:
      - union
    paths:
      - '.union/utsa.yaml'
      - '.github/workflows/union-config.yaml'

jobs:
  apply-union-config:
    name: Apply Union configuration
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: navikt/union-config@v2
        name: Apply service accounts
        with:
          manifest: .union/service_accounts.yaml